IF
	Die()
THEN
	RESPONSE #100
	        SetGlobal("RZ_SII_Cutscene_2","MYAREA",2) 
		ReallyForceSpellDead(Myself,VAMPIRE_GAS_FORM_CHANGE)
END

IF
         HPLT(Myself,10)
THEN
	RESPONSE #100
	        SetGlobal("RZ_SII_Cutscene_2","MYAREA",2) 
		ReallyForceSpellDead(Myself,VAMPIRE_BAT_FORM_CHANGE)
END

IF
        Global("RZ_Rest","LOCALS",0)
        OR(7)
             Detect([GOODCUTOFF.0.0.0.0.SUMMONED])
	     Detect([PC])
	     Detect([ALLY])
	     Detect([CONTROLLED])
             Detect([CHARMED])
             Detect([FAMILIAR])
             Detect(NearestEnemyOf(Myself))
 THEN
	RESPONSE #100
	         SetGlobal("RZ_Rest","LOCALS",1)
	         SetGlobalTimer("RZ_Rest_Timer","LOCALS",2400)
END

IF
	!GlobalTimerNotExpired("RZ_Rest_Timer","LOCALS")
	!Detect([GOODCUTOFF.0.0.0.0.SUMMONED])
	!Detect([PC])
	!Detect([ALLY])
	!Detect([CONTROLLED])
        !Detect([CHARMED])
        !Detect([FAMILIAR])
        !Detect(NearestEnemyOf(Myself))
        CombatCounter(0)
THEN
	RESPONSE #100
		SetGlobalTimer("RZ_Rest_Timer","LOCALS",3600)
		SetGlobal("RZ_Rest","LOCALS",0)
		ApplySpell(Myself,RESTORE_FULL_HEALTH)
		Rest()
END

IF
	!Allegiance(Myself,ENEMY)
	OR(18)
		AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
		AttackedBy([PC],DEFAULT)
		AttackedBy([FAMILIAR],DEFAULT)
		AttackedBy([ALLY],DEFAULT)
		AttackedBy([CONTROLLED],DEFAULT)
		AttackedBy([CHARMED],DEFAULT)
		HitBy([GOODCUTOFF.0.0.0.0.SUMMONED],CRUSHING)
		HitBy([PC],CRUSHING)
		HitBy([FAMILIAR],CRUSHING)
		HitBy([ALLY],CRUSHING)
		HitBy([CONTROLLED],CRUSHING)
		HitBy([CHARMED],CRUSHING)
		SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
		SpellCastOnMe([PC],0)
		SpellCastOnMe([FAMILIAR],0)
		SpellCastOnMe([ALLY],0)
		SpellCastOnMe([CONTROLLED],0)
		SpellCastOnMe([CHARMED],0)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("RZ_See_Enemy","LOCALS",1)
		ChangeAIScript("RZSIIWAA",OVERRIDE)
		ChangeAIScript("RZSIIATA",CLASS)
END

IF
  Global("RZ_SII_Cutscene_2","MYAREA",0)
  Detect([PC])
THEN
    RESPONSE #100
             SetGlobal("RZ_SII_Cutscene_2","MYAREA",1)
END

IF
  Global("RZ_SII_Cutscene_2","MYAREA",0)
THEN
    RESPONSE #100
END

IF
	Detect([PC])
	Global("StartingDialogue","LOCALS",0)
THEN
	RESPONSE #100
		StartDialogueNoSet(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,ENEMY)
        Detect([PC])
	!Detect([ENEMY.0.0.THIEF_ALL])
        !Detect([NEUTRAL.0.0.THIEF_ALL])
	Global("StartingDialogue","LOCALS",1)
THEN
	RESPONSE #100
	        Enemy()
		SetGlobal("RZ_See_Enemy","LOCALS",1)
		ChangeAIScript("RZSIIWAA",OVERRIDE)
		ChangeAIScript("RZSIIATA",CLASS)
		StartDialogueNoSet(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	OR(2)
             See([ENEMY.0.0.THIEF_ALL])
             See([NEUTRAL.0.0.THIEF_ALL])
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),30)
END

